#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Ao executar git commit, é mostrado as opções de mensagens válidas de commit para selecionar
# Depois disso, é executado o arquivo ./commit-msg
exec < /dev/tty && node_modules/.bin/cz --hook || true